### ISSUE TITLE
I have an issue with lxqt-runner.  Is the autosuggestions from history stored in a file read during typing? Or is the autosuggestions stored in memory?

### ISSUE THREAD

**Issue by kanliot** [lxqt/lxqt-runner#128]
My issue is the delay between typing and the characters appearing in the search dialog.  I believe that this delay is too long.   If I can't see what I'm typing, I can't press the return key, and launch a program.

Are the autosuggestions from lxqt-runner history + path + icons stored in a file read during typing? Or are the autosuggestions data stored in memory?

**Comment by tsujan** [comment]
This is a bug tracker not a forum. Please fill in the template and describe the problem clearly.
