### ISSUE TITLE
Building fails

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-runner#144]
Updated arch linux and runner isn't working anymore:
`$ lxqt-runner 
lxqt-runner: symbol lookup error: lxqt-runner: undefined symbol: _ZN2mu6ParserC2Ev`

Recompiled all LXQt components, runner fails with

```


...[ 94%] Building CXX object CMakeFiles/lxqt-runner.dir/yamlparser.cpp.o
[ 96%] Building CXX object CMakeFiles/lxqt-runner.dir/configuredialog/configuredialog.cpp.o
In file included from /home/stef/git/lxqt/lxqt-runner/providers.cpp:32:
/home/stef/git/lxqt/lxqt-runner/providers.h: In member function 'virtual bool ExternalProviderItem::compare(const QRegExp&) const':
/home/stef/git/lxqt/lxqt-runner/providers.h:322:33: warning: unused parameter 'regExp' [-Wunused-parameter]
  322 |     bool compare(const QRegExp &regExp) const {return true;} // We leave the decision to the external process
      |                  ~~~~~~~~~~~~~~~^~~~~~
/home/stef/git/lxqt/lxqt-runner/providers.cpp: In member function 'virtual bool CustomCommandItem::compare(const QRegExp&) const':
/home/stef/git/lxqt/lxqt-runner/providers.cpp:587:48: warning: unused parameter 'regExp' [-Wunused-parameter]
  587 | bool CustomCommandItem::compare(const QRegExp &regExp) const
      |                                 ~~~~~~~~~~~~~~~^~~~~~
/home/stef/git/lxqt/lxqt-runner/providers.cpp: In member function 'virtual unsigned int CustomCommandItem::rank(const QString&) const':
/home/stef/git/lxqt/lxqt-runner/providers.cpp:596:53: warning: unused parameter 'pattern' [-Wunused-parameter]
  596 | unsigned int CustomCommandItem::rank(const QString &pattern) const
      |                                      ~~~~~~~~~~~~~~~^~~~~~~
[ 98%] Building CXX object CMakeFiles/lxqt-runner.dir/LXQtAppTranslationLoader.cpp.o
/home/stef/git/lxqt/lxqt-runner/providers.cpp: At global scope:
/home/stef/git/lxqt/lxqt-runner/providers.cpp:796:17: error: cannot derive from 'final' base 'mu::Parser' in derived type 'MathItem::Parser'
  796 | class MathItem::Parser : private mu::Parser
      |                 ^~~~~~
/home/stef/git/lxqt/lxqt-runner/providers.cpp: In constructor 'ExternalProvider::ExternalProvider(QString, QString)':
/home/stef/git/lxqt/lxqt-runner/providers.cpp:975:44: warning: 'void QProcess::start(const QString&, QIODevice::OpenMode)' is deprecated: Use QProcess::start(const QString &program, const QStringList &arguments,OpenMode mode = ReadWrite) instead [-Wdeprecated-declarations]
  975 |     mExternalProcess->start(externalProgram);
      |                                            ^
In file included from /usr/include/qt/QtCore/QProcess:1,
                 from /home/stef/git/lxqt/lxqt-runner/providers.cpp:39:
/usr/include/qt/QtCore/qprocess.h:168:10: note: declared here
  168 |     void start(const QString &command, OpenMode mode = ReadWrite);
      |          ^~~~~
make[2]: *** [CMakeFiles/lxqt-runner.dir/build.make:324: CMakeFiles/lxqt-runner.dir/providers.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/stef/git/lxqt/lxqt-runner/configuredialog/configuredialog.cpp: In constructor 'ConfigureDialog::ConfigureDialog(QSettings*, const QString&, QWidget*)':
/home/stef/git/lxqt/lxqt-runner/configuredialog/configuredialog.cpp:70:39: warning: 'int QDesktopWidget::screenCount() const' is deprecated: Use QGuiApplication::screens() [-Wdeprecated-declarations]
   70 |     int monCnt = desktop->screenCount();
      |                                       ^
In file included from /usr/include/qt/QtWidgets/QDesktopWidget:1,
                 from /home/stef/git/lxqt/lxqt-runner/configuredialog/configuredialog.cpp:36:
/usr/include/qt/QtWidgets/qdesktopwidget.h:118:12: note: declared here
  118 | inline int QDesktopWidget::screenCount() const
      |            ^~~~~~~~~~~~~~
make[1]: *** [CMakeFiles/Makefile2:118: CMakeFiles/lxqt-runner.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```

##### System Information

* Distribution & Version: up-to date arch, git LXQt
* Qt Version: 5.15
 qt5-base    5.15.0-3
```
$ cat /var/log/pacman.log |grep qt5
....
[2020-06-14T11:19:15+0200] [ALPM] upgraded qt5-base (5.14.2-3 -> 5.15.0-3)
[2020-06-14T11:19:15+0200] [ALPM] upgraded qt5-svg (5.14.2-1 -> 5.15.0-1)
[2020-06-14T11:19:15+0200] [ALPM] upgraded qt5-declarative (5.14.2-1 -> 5.15.0-1)
[2020-06-14T11:19:15+0200] [ALPM] upgraded qt5-x11extras (5.14.2-1 -> 5.15.0-1)
[2020-06-14T11:19:15+0200] [ALPM] upgraded qt5-multimedia (5.14.2-1 -> 5.15.0-1)
[2020-06-14T11:19:15+0200] [ALPM] upgraded qt5-speech (5.14.2-1 -> 5.15.0-1)
[2020-06-14T11:19:16+0200] [ALPM] upgraded qt5-webchannel (5.14.2-1 -> 5.15.0-1)
[2020-06-14T11:19:16+0200] [ALPM] upgraded qt5-location (5.14.2-2 -> 5.15.0-1)
[2020-06-14T11:19:17+0200] [ALPM] upgraded qt5-webengine (5.14.2-3 -> 5.15.0-1)
[2020-06-14T11:19:21+0200] [ALPM] upgraded qt5-wayland (5.14.2-1 -> 5.15.0-1)
[2020-06-14T11:19:23+0200] [ALPM] upgraded python2-sip-pyqt5 (4.19.22-1 -> 4.19.23-1)
[2020-06-14T11:19:24+0200] [ALPM] upgraded python2-pyqt5 (5.14.2-1 -> 5.15.0-2)
[2020-06-14T11:19:27+0200] [ALPM] upgraded qt5-xmlpatterns (5.14.2-1 -> 5.15.0-1)
[2020-06-14T11:19:27+0200] [ALPM] upgraded qt5-quickcontrols (5.14.2-1 -> 5.15.0-1)
[2020-06-14T11:19:29+0200] [ALPM] upgraded qt5-graphicaleffects (5.14.2-1 -> 5.15.0-1)
[2020-06-14T11:19:29+0200] [ALPM] upgraded qt5-quickcontrols2 (5.14.2-1 -> 5.15.0-1)
[2020-06-14T11:19:33+0200] [ALPM] upgraded qt5-sensors (5.14.2-1 -> 5.15.0-1)
[2020-06-14T11:19:33+0200] [ALPM] upgraded qt5-webkit (5.212.0alpha4-4 -> 5.212.0alpha4-6)
[2020-06-14T11:19:33+0200] [ALPM] upgraded qt5-script (5.14.2-1 -> 5.15.0-1)
[2020-06-14T11:19:46+0200] [ALPM] upgraded python-pyqt5-sip (12.7.2-1 -> 12.8.0-1)
[2020-06-14T11:19:46+0200] [ALPM] upgraded python-pyqt5 (5.14.2-1 -> 5.15.0-2)
[2020-06-14T11:19:46+0200] [ALPM] upgraded qt5-imageformats (5.14.2-1 -> 5.15.0-1)
[2020-06-14T11:19:46+0200] [ALPM] upgraded qt5-serialport (5.14.2-1 -> 5.15.0-1)
[2020-06-14T11:19:46+0200] [ALPM] upgraded qt5-tools (5.14.2-2 -> 5.15.0-2)
[2020-06-14T11:19:47+0200] [ALPM] upgraded qt5-translations (5.14.2-1 -> 5.15.0-1)


```

**Comment by tsujan** [comment]
It's OK here, with the same version of Qt.

Do you have `muparser`?

**Comment by tsujan** [comment]
BTW and quite unrelated to this: If I correctly remember, most of the time, if Qt's second version is updated, you'll only need to recompile `libqtxdg`, `liblxqt` and `lxqt-qtplugin`, in that order.

But if you want to upgrade to git LXQt, yes, you should compile and replace all packages in the order you probably know about (libqtxdg → lxqt-build-tools → liblxqt → libfm-qt → pcmanfm-qt →...).

**Comment by stefonarch** [comment]
Build order starts with

```
        libqtxdg \
        lxqt-build-tools \
        liblxqt \
        libsysstat \
        libfm-qt \
        lxqt-themes \
        lxqt-qtplugin \
...
```

muparser is installed. 
Just tried lxqt-runner from arch repo, same error when launching.

**Comment by stefonarch** [comment]
not sure about all those:

```
 $ lxqt-runner 
QDBusMarshaller: cannot add an invalid QVariant
QDBusConnection: error: could not send message to service "org.freedesktop.login1" path "/org/freedesktop/login1" interface "org.freedesktop.login1.Manager" member "CanHibernate": Marshalling failed: Variant containing QVariant::Invalid passed in arguments
** Dbus error **************************
Error name  "org.freedesktop.DBus.Error.Failed"
Error msg   "Marshalling failed: Variant containing QVariant::Invalid passed in arguments"
****************************************
QDBusMarshaller: cannot add an invalid QVariant
QDBusConnection: error: could not send message to service "org.freedesktop.login1" path "/org/freedesktop/login1" interface "org.freedesktop.login1.Manager" member "CanSuspend": Marshalling failed: Variant containing QVariant::Invalid passed in arguments
** Dbus error **************************
Error name  "org.freedesktop.DBus.Error.Failed"
Error msg   "Marshalling failed: Variant containing QVariant::Invalid passed in arguments"
****************************************
libpng warning: iCCP: known incorrect sRGB profile
```

**Comment by tsujan** [comment]
> EDIT: downgrade again to muparser-2.2.6-2 and it compiles again well

I have muparser 2.2.6-2 -- 2.3.1-1 hasn't come here yet.

If muparser 2.3.1 is OK but contains a backward-incompatible change, we might need to do something.

@yan12125, if I correctly remember, you usually have the latest Arch packages. Do you know what the problem is?

**Comment by tsujan** [comment]
> not sure about all those:

I don't get any of them here, probably because your system is more up-to-date than mine. @yan12125  might be able to clarify everything.

**Comment by yan12125** [comment]
I can reproduce the `undefined symbol: _ZN2mu6ParserC2Ev` error and the build failure with muparser 2.3.1. Let me check out what changes in muparser.

**Comment by stefonarch** [comment]
The latest 2 doesn't work:

```
1: muparser-2.3.1-1  (from ALA)
2: muparser-2.3.0-1  (from ALA)
3: muparser-2.2.6-2  [installed]

```

**Comment by yan12125** [comment]
Seems an upstream issue and the key change is reverted: https://github.com/beltoforion/muparser/commit/09474d22ea5b3cdee4f1ea14150c6d878249dbfd.

**Comment by tsujan** [comment]
@yan12125, you were so fast :) Thank you very much!

**Comment by yan12125** [comment]
A workaround is temporarily disabling the muparser integration with `-DRUNNER_MATH=OFF`. As muparser has entered stable repositories of Arch Linux, I uploaded lxqt-runner 0.15.0-2 with this change.

**Comment by beltoforion** [comment]
I have published a new prerelease of muparser. The release of the final version will be within the next 2-4 weeks. Please let me know if you run into further comatibility issues.

**Comment by yan12125** [comment]
> I have published a new prerelease of muparser.

Cool, thanks!

> If version 2.3.0 has already slipped into arch linux

FYI, I have asked them if muparser can be updated to `v2.3.1_prerelease2`.

**Comment by yan12125** [comment]
muparser is updated to 2.3.2 on Arch and everything should work again. Thanks a lot @beltoforion!

Meanwhile, I re-enabled muparser integration in the lxqt-runner package on Arch.

**Comment by alexandre1985** [comment]
Thank you. Doing `pacman -Syy muparser` did solve this.
After the reinstall you have to go to the Configuration Center > Session Configuration > Click on 'Runner' and start/activate it

**Comment by kapitaali** [comment]
> not sure about all those:
> 
> ```
>  $ lxqt-runner 
> QDBusMarshaller: cannot add an invalid QVariant
> QDBusConnection: error: could not send message to service "org.freedesktop.login1" path "/org/freedesktop/login1" interface "org.freedesktop.login1.Manager" member "CanHibernate": Marshalling failed: Variant containing QVariant::Invalid passed in arguments
> ** Dbus error **************************
> Error name  "org.freedesktop.DBus.Error.Failed"
> Error msg   "Marshalling failed: Variant containing QVariant::Invalid passed in arguments"
> ****************************************
> QDBusMarshaller: cannot add an invalid QVariant
> QDBusConnection: error: could not send message to service "org.freedesktop.login1" path "/org/freedesktop/login1" interface "org.freedesktop.login1.Manager" member "CanSuspend": Marshalling failed: Variant containing QVariant::Invalid passed in arguments
> ** Dbus error **************************
> Error name  "org.freedesktop.DBus.Error.Failed"
> Error msg   "Marshalling failed: Variant containing QVariant::Invalid passed in arguments"
> ****************************************
> libpng warning: iCCP: known incorrect sRGB profile
> ```

getting this same error with default lxqt + debian 11 install

**Comment by stefonarch** [comment]
I can confirm that, on a VM with debian testing and LXQt 0.16 -  but the runner works so I'd say ignore it and hope debian upgrade LXQt at some point.

**Comment by kapitaali** [comment]
How can I test this? I have created a launcher shortcut on my desktop and clicking it does nothing.

**Comment by tsujan** [comment]
> and hope debian upgrade LXQt at some point.

muparser too. It seems it has no active maintainer in Debian.

**Comment by stefonarch** [comment]
> How can I test this? I have created a launcher shortcut on my desktop and clicking it does nothing.

The runner doesn't need any launcher, it's always active, in "session settings" under modules you can start or stop it, or disable it. default shortcut is alt+f2

**Comment by kapitaali** [comment]
Ok thank you, I must have misconfigured something.
