### ISSUE TITLE
Input not selected anymore after "copy calculation result"

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-runner#178]
In runner last text or calculation inserted is shown again selected when reopening  when no click has be done. Just typing will cancel all. When copying a calculation result at reopening runner shows calculation but not selected. This doesn't happen when result is not copied. 

##### Expected Behavior

Previous stuff in runner is cleared or selected
##### Current Behavior

After  copying calculation result input has to be cleared manually before typing (cltr+a or else)
##### Possible Solution

Probably it's the click that usually opens the application? Could well be that it was always like that but nobody ever clicked the result.

##### Steps to Reproduce (for bugs)

1. Open runner and type 3+5=
2. result is shown
3. click to copy 
4. close and reopen runner -  before reusing calculation has to be deleted
5. same as above with no copy, 
6. reopen and typing is ok

##### System Information

* Distribution & Version: latest git with https://github.com/lxqt/lxqt-runner/commit/d7eb2d11fa951871c3ac1b582bf1ad5b4da70d31#commitcomment-47311739

**Comment by tsujan** [comment]
> Could well be that it was always like that but nobody ever clicked the result.

Yes, I checked without the "copy-to-clipboard" patch. Previously, no one had a reason to click into the view-item with a calculation: if the click is done and the runner is made hidden, the text won't be selected on showing the runner.

**Comment by stefonarch** [comment]
No idea if this doable, but as the other clicks on the application chosen give no issue, do the same, for example a pop-up "result copied to clipboard" or else.

**Comment by tsujan** [comment]
@stefonarch 
The fix is easy. I'll make a simple PR soon.

**Comment by stefonarch** [comment]
It works, but clears all. Is it possible not to clear it but to select all?
I sometimes use again the same calculation as before, changing only the last input, using arrows.

**Comment by tsujan** [comment]
I just let it be exactly like other cases: you search an app, click its item and the entry is cleared. If you don't click the item, the entry will be selected next time. Making an exception for this case is possible but requires an ugly code.

**Comment by stefonarch** [comment]
I forgot that it't the same with clicking the application.

**Comment by tsujan** [comment]
I'll check if making an exception is possible without an ugly code. I'm not sure but it seems that not clearing the text can be useful in the case of calculations -- as you said.

**Comment by tsujan** [comment]
Yes, it's possible with three small lines of code.

Let's wait for https://github.com/lxqt/lxqt-runner/pull/176 to de decided because one of those lines is in a conflict with that PR.

**Comment by tsujan** [comment]
Rebased and done as @stefonarch told: Math result is selected on showing the Runner, instead of being cleared.

**Comment by stefonarch** [comment]
Thanks :1st_place_medal:
