### ISSUE TITLE
Home and End keys don't work when typing in lxqt-runner

### ISSUE THREAD

**Issue by ssrublev** [lxqt/lxqt-runner#213]
Hello! I have noticed that lxqt-runner don't react to Home and End buttons when I type commands in the runner after activating it with Alt+F2. 

I cannot, e. g. type a command and then press Shift+Home to select the text from beginning. So the End key.

Tested in two Fedora installations. lxqt-runner.x86_64 0.17.0-1.fc35 Fedora-LXQt official spin https://spins.fedoraproject.org/en/lxqt/

**Comment by tsujan** [comment]
You may have an old version. `Home` selects the first item and `End` selects the last.

When opening an issue, please fill in the template (→ "Package version:").

**Comment by tsujan** [comment]
Oh, sorry, you'd mentioned the version in your comment. Yes, 0.17.0 is outdated.

If you use the issue template, everything will be clear by a glance.
