### ISSUE TITLE
Runner window moved to wrong (0,0) position after search

### ISSUE THREAD

**Issue by palinek** [lxqt/lxqt-runner#220]
After recent upgrade to 1.1 I'm seeing misbehavior of the window placement after the search:

https://user-images.githubusercontent.com/10990929/165452803-877522b6-029c-4c48-84c8-1a6a927709c8.mp4

I'm clueless why this is happening as from runners source code point of view, it should work. Maybe for some reason WM (openbox in this case) decides to move the window ?!

##### Expected Behavior
Correctly positioned window.

##### Current Behavior
Sometimes wrongly positioned window.

##### Possible Solution
I have analyzed the behavior, trying to find the bug in runner. But most I could achieve was just a workaround. I'll make PR soon.

##### Steps to Reproduce (for bugs)
I can't find a pattern to reproduce it 100%, but I'm getting a high rate for reproducing it by following:
1. freshly start runner process
2. invoke runner (shortcut)
3. type for search & wait for results
4. click on settings & change the position configuration & close settings
5. invoke runner (shortcut)
6. type for search & wait for results
7. observe runner window moving to wrong position

##### System Information
* Distribution & Version: debian testing
* Qt Version: 5.15.2
* liblxqt Version: git master
* lxqt-build-tools Version: git master
* Package version: git master

**Comment by stefonarch** [comment]
The patch works fine with openbox he

> After recent upgrade to 1.1

Didn't you use GH master? Because for me it started in November on both machines.

**Comment by palinek** [comment]
> Didn't you use GH master? 

No. I'm using the released versions. Just for developing & testing I'm using git master.

**Comment by stefonarch** [comment]
Maybe is was triggered by some code from us then? It started both on debian and arch for me.

**Comment by tsujan** [comment]
There has been no recent change in lxqt-runner related to it. Also, you saw a similar thing with LXQt 0.16 (→ https://github.com/lxqt/lxqt/discussions/2134#discussioncomment-1682940).

A change in X11 may have intensified it. Why with Openbox, I have no idea.

**Comment by stefonarch** [comment]
> you saw a similar thing with LXQt 0.16

Forgot about that ;)
It's just strange that it pops up now with 1.1
