### ISSUE TITLE
not possible to build lxqt-runner alone?

### ISSUE THREAD

**Issue by kanliot** [lxqt/lxqt-runner#224]
##### Expected Behavior

I installed 1.1 lxqt-runner source through git, then installed `libkf5windowsystem-dev`
neither cmake nor make accepts  building this project. 

* Distribution & Version: 1.1 

also- running cmake doesn't seem to help anything.  I am sorry for not knowing more about cmake to make a good effort here. 

I expect if I followed https://github.com/lxqt/lxqt/wiki/Building-from-source the build guide on the lxqt wiki it would work well.  Since i've followed build instructions on the `README.md` in this git repo, please confirm what I am doing wrong. 

Again, all I want to know is what I'm doing wrong.

**Comment by tsujan** [comment]
> neither cmake nor make accepts building this project.

cmake shows the error(s), and make won't work when cmake doesn't.

Closing this because it's rather a question about cmake, without enough info. Please use https://github.com/lxqt/lxqt/discussions for questions.
