### ISSUE TITLE
Two icons contain ICC profiles under an LGPL-2.1-incompatible license

### ISSUE THREAD

**Issue by ArrayBolt3** [lxqt/lxqt-runner#241]
There are two files in lxqt-runner, `vbox-icons/state_running_16px.png` and `vbox-icons/vrdp_16px.png` that contain an embedded ICC color profile from Adobe Photoshop (as determined by running `exiftool` on the two files). Adobe's ICC color profile is under the following license agreement: https://www.adobe.com/support/downloads/iccprofiles/icc_eula_win_end.html

Part of the license agreement reads as follows (emphasis added):

> No other distribution of the Software is allowed; including, without limitation, distribution of the Software when incorporated into or bundled with any application software. **You may not modify the Software.**

This contradicts the LGPL-2.1 license, which states (emphasis added):

> You may modify your copy or copies of the Library **or any portion of it,** thus forming a work based on the Library, and copy and distribute such modifications or work under the terms of Section 1 above, provided that you also meet all of these conditions...

Additionally, Adobe's license contradicts the Debian Free Software Guidelines, which states "The license must allow modifications and derived works, and must allow them to be distributed under the same terms as the license of the original software." This makes the Adobe ICC profile not allowed to be included in Ubuntu's software archives. (Currently I'm replacing the ICC profile in Lubuntu with GIMP's public domain ICC sRGB profile to fix this.)

While technically lxqt-runner's current use of the profile is (I believe) not in violation of Adobe's license, it does restrict freedoms granted by the LGPL and the DFSG. I believe this is probably a bug in lxqt-runner, and would like to request that the Adobe ICC profile be replaced with GIMP's public domain ICC sRGB profile. I'm able to do this by simply opening the files in GIMP, allowing GIMP to convert the color profile to the public domain one, and then exporting the file as a .png and overwriting the original. This is pretty easy, and would also greatly reduce the workload for maintaining lxqt-runner in Lubuntu.

**Comment by yan12125** [comment]
Most likely those icon files are copied from VirtualBox: https://www.virtualbox.org/svn/vbox/trunk/src/VBox/Frontends/VirtualBox/images/. `state_running_16px.png` and `vrdp_16px.png` there have different sizes than ones in this repo. Could you check if icons there uses an incompatible license or not?

**Comment by ArrayBolt3** [comment]
Tested both files mentioned along with vrdp_24px.png and vrdp_32px.png. None of the four files contained the Adobe ICC profile.

**Comment by yan12125** [comment]
Thanks! I will update icons in this repo after figuring out a way to download icons without clicking one by one.

**Comment by yan12125** [comment]
Fix at https://github.com/lxqt/lxqt-runner/pull/242. Could you check updated icons still have a compatible license?

**Comment by ArrayBolt3** [comment]
Sorry, got busy and missed this. I can verify that the new icons are good. Thank you so much!
