### ISSUE TITLE
Fcitx5 doesn't work on Telegram if I open it through lxqt-runner

### ISSUE THREAD

**Issue by glu8716** [lxqt/lxqt-runner#265]
##### Expected Behavior

When I open Telegram through lxqt-runner I should be able to switch between Fcitx5 input methods.
##### Current Behavior

Fcitx5 doesn't let me switch between input methods.
##### Steps to Reproduce (for bugs)

1. Open lxqt-runner
2. Run telegram-desktop
3. Try to switch between input methods with Fcitx5

##### Context

All the needed environment variables are set through the Lxqt session settings:
![image](https://github.com/lxqt/lxqt-runner/assets/33501455/da005b9f-4cda-4963-b9e5-3ed8e8bdac25)
Fcitx5 works fine on every program launched with lxqt-runner, except for Telegram. If I launch Telegram from the terminal or from the .desktop file in /usr/share/applications Fcitx5 works fine. I'm not sure if this is a lxqt-runner problem or a Telegram problem. I'm reporting the problem here first, but if it's not related to lxqt-runner I'll try to reach the Telegram client developers instead.

##### System Information

* Distribution & Version: Artix
* Kernel: 6.5.4
* Qt Version: 5.15.10
* liblxqt Version: 1.3.0
* lxqt-build-tools Version: 0.13.0
* Package version: 1.3.0

**Comment by tsujan** [comment]
This should be a new bug in Telegram. It isn't limited to LXQt Runner.

Since some version, Telegram ignores the Qt plugins when run through LXQt Panel's main menu or LXQt Runner. You can see that by calling the file dialog from inside Telegram: it's Qt's default dialog.

But, Telegram works fine when run from inside PCManFM-Qt; I'm not sure why (perhaps because of a code related to GNOME, which uses GLib, like PCManFM-Qt does).

**Comment by glu8716** [comment]
I see, thanks for the explanation. Do you know if this is a known thing and there is already a report?

**Comment by stefonarch** [comment]
> You can see that by calling the file dialog from inside Telegram: it's Qt's default dialog.

That is not the case here, I get always LXQt's filedialog. Maybe wayland related?

**Comment by tsujan** [comment]
> Maybe wayland related?

Yes, maybe.

Anyway, apps don't ignore Qt plugins automatically; something in their codes should enforce that. I don't know how and why Telegram does it.

> Do you know if this is a known thing and there is already a report?

No, I haven't searched Telegram's bug tracker.

**Comment by tsujan** [comment]
BTW, Telegram also had (or has) a bug (under X11), which made it crash on exiting if ii was quit while its window was shown. Maybe related.

**Comment by glu8716** [comment]
> No, I haven't searched Telegram's bug tracker.
I see. I'll look at it, if there's none I'll open it.

**Comment by tsujan** [comment]
> I see. I'll look at it, if there's none I'll open it.

The reply at Telegram's bug tracker about D-Bus reminded me of a fact that I'd forgotten when writing the above comments: Telegram is a Qt6 app now. I use the git Qt6-based PCManFM-Qt (alongside LXQt libraries from Qt6 branches), while LXQt Runner and LXQt Panel are still Qt5 apps.

However, that doesn't explain the problem because Arch's `fcitx5-qt` installs both Qt5 and Qt6 plugins. Moreover, other Qt6 apps that depend on D-Bus (like FeatherPad) work fine here, and you said that fcitx5 works when Telegram is launched through a terminal. That's not normal.

**Comment by glu8716** [comment]
He might be right about D-Bus. I've just tried to run lxqt-terminal through the terminal and I can see some errors about D-Bus:
```
systemd: "CanHibernate" = "na"
** Dbus error **************************
Error name  "org.freedesktop.DBus.Error.InvalidArgs"
Error msg   "No such interface “org.freedesktop.DBus.Properties”"
****************************************
dbusCall: QDBusInterface is invalid "org.freedesktop.ConsoleKit" "/org/freedesktop/ConsoleKit/Manager" "org.freedesktop.ConsoleKit.Manager" "CanHibernate"
systemd: "CanSuspend" = "yes"
```

**Comment by tsujan** [comment]
All I can say for now is that I see no error message here.

**Comment by glu8716** [comment]
I found a solution, and that is removing `DBusActivatable=true` from the .desktop file of Telegram. By doing that Fcitx5 works fine when Telegram is launched with lxqt-runner. That is not the case for the Application Menu though.

**Comment by tsujan** [comment]
Happy to know that you've found a workaround.

We still need to check whether `libqtxdg`'s handling of desktop files has a problem. I have my suspicions because `libfm-qt` inherits GLib's handling of desktop files and doesn't show this problem. That was the only reason I kept the report open.

@luis-pereira ?

**Comment by glu8716** [comment]
Don't know if you have been following the thread on the Telegram's github, but apparently running `dbus-update-activation-environment --all` also fixes the problem, for the Application Menu too.

**Comment by luis-pereira** [comment]
@tsujan How does libfm-qt run an application ? By reading the .desktop file and or by running the executable ? Does libfm-qt takes `DBusActivatable` into account  or just uses the `Exec` method ?

`libqtxdg` honors `DBusActivatable`. If the `DBusActivatable` method fails we [break the standard](https://github.com/lxqt/libqtxdg/blob/fb5ef48fcc9eab3ecf6ee539bc24d745b0f3f786/src/qtxdg/xdgdesktopfile.cpp#L500) and try the `Exec` method. 

My quick findings:
```
[lpereira@maxwell src]$ qtxdg-desktop-file-start /usr/share/applications/org.telegram.desktop.desktop 
XdgDesktopFileData::startByDBus(timeout=1500): failed to start org.freedesktop.Application/usr/share/applications/org.telegram.desktop.desktop: QDBusMessage(type=Error, service=, error name=org.freedesktop.DBus.Error.NoReply, error message=Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken., signature=s, contents=("Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.") )
```
and fctix5 **doesn't work**.

After running `dbus-update-activation-environment --all`
I get  the same error with `qtxdg-desktop-file-start` but fcitx5 **works**.

`DBusActivatable` fallbacks to `Exec` in case of error. 

By changing the `DBusActivatable` to false, fcitx5 **works**.

It seems that although XdgDesktopFileData::startByDBus` exits with a timeout error it somehow continues execution.

p.s. I'm on a netbook. Can't compile `libqtxdg`. @palinek Can you pls take a look ?

**Comment by tsujan** [comment]
> Does libfm-qt takes DBusActivatable into account...? libqtxdg honors DBusActivatable...

libfm-qt ignores it. So, according to what you explained, it behave like launching Telegram from a terminal because it's less thorough than `libqtxdg`. Thanks!

**Comment by luis-pereira** [comment]
> libfm-qt ignores it. So, according to what you explained, it behaves like launching Telegram from a terminal because it's less thorough than `libqtxdg`. Thanks!

It's probably using the `Exec`.

Under KDE the running telegram with `qtxdg-desktop-file-start`  makes fcitx5 work, although we get the same timeout errors. So, I suspect that KDE is somehow  updating the activation environment.  Most probably  LXQt needs to do it also.

**Comment by glu8716** [comment]
Today I've also noticed that Firejail doesn't apply its profile to Telegram if launched from lxqt-runner.

**Comment by luis-pereira** [comment]
Wrote a patch that calls `dbus-update-activation-environment` during `lxqt-session`. Will try it for a couple of days and if it goes Ok make a PR. Plasma also updates the dbus activation environment.
The issue with `firejail` willl probably be fixed.

**Comment by tsujan** [comment]
> Wrote a patch that calls dbus-update-activation-environment during lxqt-session.

Nice!

Is it safe under all circumstances and on X11 and Wayland alike? If yes, I think there's no need to an extra option for it.

**Comment by luis-pereira** [comment]
> Is it safe under all circumstances and on X11 and Wayland alike? If yes, I think there's no need to an extra option for it.

Yes, AFAIK. I only tested with X11. With Wayland it should also work Ok.

@glu8716  PR here: https://github.com/lxqt/lxqt-session/pull/477
