### ISSUE TITLE
I'm still having problem with Telegram and firejail if launched from lxqt-runner

### ISSUE THREAD

**Issue by glu8716** [lxqt/lxqt-runner#270]
The new lxqt-session update that introduced the patch for `dbus-update-activation-environment` fixes the Fcitx problem on Telegram, thanks! 
However as long as `DBusActivatable` is set to `true` in the .desktop file of Telegram the program doesn't inherit the firejail sandbox if launched through lxqt-runner as I stated in this comment https://github.com/lxqt/lxqt-runner/issues/265#issuecomment-1752174260. Unfortunately the patch didn't fix this @luis-pereira and I still need to set `DBusActivatable` to `false`.
Everything works fine if Telegram is launched through the terminal or through the file manager.

**Comment by luis-pereira** [comment]
@glu8716  Thanks for you report. I will take a look at it, probably during the weekend.
I didn't test it with firejail. I don't use firejail.

**Comment by glu8716** [comment]
Hi, any news on this?

**Comment by luis-pereira** [comment]
Sadly, no. I was away from LXQt development for a while.
Catching up now.

**Comment by luis-pereira** [comment]
@glu8716 
This is a known firejail configuration FAQ.
Just follow the [instructions](https://github.com/netblue30/firejail/wiki/Frequently-Asked-Questions#how-can-i-enable-fcitx). Just did, and it makes it work.
